FROM node:18-alpine

# Installation de json-server globalement
RUN npm install -g json-server

WORKDIR /app

#  chercher db.json dans le dossier api-http
COPY api-http/db.json .

# Expose le port de l'API
EXPOSE 8081

# Commande pour lancer l'API
CMD ["json-server", "--watch", "db.json", "--port", "8081", "--host", "0.0.0.0"]